#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_font.sh -- OMF font -> 3DO CEL set + C header pipeline.
#
# Steps:
#   1. dump_font dump     -> 95 PNGs (g32.png..g126.png) + manifest in stage dir
#   2. 3it to-cel         -> 95 CELs in takeme/Art/FONT/
#   3. C header gen       -> port_3do/src/font_data.h with the CEL paths array
#
# Runtime: blit_text.c LoadCels each path, builds a CCB chain at draw time.
# Color tinting handled at runtime via CCB PIXC (the CELs are emitted as
# white-on-transparent; PIXC modulates the white to whatever color the
# caller requested).
#
# Usage:
#   ./run_pipeline_font.sh small        # CHARSMAL.DAT  (6x6, padded to 8x8 cell)
#   ./run_pipeline_font.sh large        # GRAPHCHR.DAT  (8x8 cell)
#
# Default: small.

set -u

VARIANT="${1:-small}"
case "$VARIANT" in
    small)
        SRC="${OMF_DATA}/CHARSMAL.DAT"
        FONT_H=6
        CEL_SUBDIR="FONT_SMALL"
        HEADER_NAME="font_small_data"
        C_PREFIX="font_small"
        ;;
    large)
        SRC="${OMF_DATA}/GRAPHCHR.DAT"
        FONT_H=8
        CEL_SUBDIR="FONT_LARGE"
        HEADER_NAME="font_large_data"
        C_PREFIX="font_large"
        ;;
    *)
        echo "Usage: $0 [small|large]"
        exit 1
        ;;
esac

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_FONT="$SCRIPT_DIR/build/dump_font"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

STAGE_DIR="/tmp/${C_PREFIX}_stage"
CEL_DIR="$PROJ_ROOT/takeme/Art/$CEL_SUBDIR"
HEADER="$PROJ_ROOT/src/${HEADER_NAME}.h"

if [ ! -x "$DUMP_FONT" ]; then
    echo "dump_font not built; run 'make build/dump_font' first." >&2
    exit 1
fi
if [ ! -x "$THREE_IT" ]; then
    echo "3it not found at $THREE_IT" >&2
    exit 1
fi
if [ ! -f "$SRC" ]; then
    echo "source font not found: $SRC" >&2
    exit 1
fi

rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR" "$CEL_DIR"

echo "[1/3] dump_font $SRC h=$FONT_H -> $STAGE_DIR"
"$DUMP_FONT" dump "$SRC" "$FONT_H" "$STAGE_DIR" || { echo "dump_font failed"; exit 1; }

echo "[2/3] 3it to-cel each PNG -> $CEL_DIR"
ok=0
fail=0
total_bytes=0
for png in "$STAGE_DIR"/g*.png; do
    [ -f "$png" ] || continue
    base=$(basename "$png" .png)
    out="$CEL_DIR/${base}.CEL"
    if "$THREE_IT" to-cel --find-smallest regular --output-path "$out" "$png" \
            > /dev/null 2>&1; then
        ok=$((ok + 1))
        sz=$(stat -c%s "$out")
        total_bytes=$((total_bytes + sz))
    else
        echo "  $base.PNG -> FAILED"
        fail=$((fail + 1))
    fi
done
echo "  $ok OK, $fail failed, total CEL bytes = $total_bytes"

echo "[3/3] write C header -> $HEADER"
{
    echo "/* Auto-generated by port_3do/host_tools/run_pipeline_font.sh -- do NOT edit. */"
    echo "/* source: $SRC  font_h=$FONT_H  cel_dir=Art/$CEL_SUBDIR */"
    echo "#ifndef ${C_PREFIX^^}_DATA_H"
    echo "#define ${C_PREFIX^^}_DATA_H"
    echo ""
    echo "#define ${C_PREFIX^^}_FIRST_ASCII   32"
    echo "#define ${C_PREFIX^^}_GLYPH_COUNT   95"
    echo "#define ${C_PREFIX^^}_CELL_PAD      8        /* CEL native dim */"
    echo "#define ${C_PREFIX^^}_GLYPH_W       $FONT_H  /* visible width  */"
    echo "#define ${C_PREFIX^^}_GLYPH_H       $FONT_H  /* visible height */"
    echo ""
    echo "/* CEL paths on the 3DO filesystem. Index: ascii - ${C_PREFIX^^}_FIRST_ASCII. */"
    echo "static const char *${C_PREFIX}_cel_paths[${C_PREFIX^^}_GLYPH_COUNT] = {"
    for ch in $(seq 32 126); do
        printf '    "Art/%s/g%d.CEL",\n' "$CEL_SUBDIR" "$ch"
    done
    echo "};"
    echo ""
    echo "#endif /* ${C_PREFIX^^}_DATA_H */"
} > "$HEADER"

echo "Pipeline OK. Inspect:"
echo "  $CEL_DIR/"
echo "  $HEADER"
