#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline.sh — full OMF→3DO HAR animation pipeline driver.
#
# Steps (per HAR/move):
#   1. dump_har dump     → PNGs + manifest.txt in stage dir
#   2. 3it to-cel        → one CEL per PNG into takeme/Art/HAR_<name>/
#   3. C header gen      → port_3do/src/<name>_data.h with frame arrays
#
# The C header is what hello.c #includes to drive playback on the 3DO. It
# avoids parsing manifest.txt at runtime on the 12.5MHz ARM60.
#
# Usage:
#   ./run_pipeline.sh <har_name> <FIGHTRn.AF> <ARENAm.BK> <move_id>
# Example:
#   ./run_pipeline.sh jaguar ${OMF_DATA}/FIGHTR0.AF ${OMF_DATA}/ARENA0.BK 1

set -u  # no -e: 3it may exit non-zero on individual files and we want to continue

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <har_name> <AF_file> <BK_file> <move_id>"
    exit 1
fi

NAME="$1"
AF="$2"
BK="$3"
MOVE="$4"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_HAR="$SCRIPT_DIR/build/dump_har"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

STAGE_DIR="/tmp/${NAME}_stage"
CEL_DIR="$PROJ_ROOT/takeme/Art/HAR_$(echo "$NAME" | tr '[:lower:]' '[:upper:]')"
HEADER="$PROJ_ROOT/src/${NAME}_data.h"

mkdir -p "$STAGE_DIR" "$CEL_DIR"

echo "[1/3] dump_har dump $AF $BK move=$MOVE -> $STAGE_DIR"
"$DUMP_HAR" dump "$AF" "$BK" "$MOVE" "$STAGE_DIR" || { echo "dump_har failed"; exit 1; }

echo "[2/3] convert PNGs to CEL via 3it -> $CEL_DIR"
for png in "$STAGE_DIR"/frame_*.png; do
    [ -f "$png" ] || continue
    base=$(basename "$png" .png)
    out="$CEL_DIR/${base}.CEL"
    "$THREE_IT" to-cel --find-smallest regular --output-path "$out" "$png" \
        > /dev/null 2>&1 \
        && echo "  $base.PNG -> $base.CEL ($(stat -c%s "$out") bytes)" \
        || echo "  $base.PNG -> FAILED"
done

echo "[3/3] write C header -> $HEADER"
NAME_UPPER=$(echo "$NAME" | tr '[:lower:]' '[:upper:]')
ANIM_STRING=$(grep '^# anim_string:' "$STAGE_DIR/manifest.txt" | sed 's/^# anim_string: //')
{
    echo "/* Auto-generated by port_3do/host_tools/run_pipeline.sh -- do NOT edit. */"
    echo "/* HAR=$NAME move=$MOVE AF=$AF BK=$BK */"
    echo "#ifndef ${NAME_UPPER}_DATA_H"
    echo "#define ${NAME_UPPER}_DATA_H"
    echo ""
    echo "/* OMF anim_string: $ANIM_STRING */"
    echo "static const char ${NAME}_anim_string[] = \"$ANIM_STRING\";"
    echo ""
    echo "typedef struct {"
    echo "    const char *cel_path;       /* 3DO filesystem path */"
    echo "    short pos_x, pos_y;         /* per-frame pixel offset from anchor */"
    echo "    short w, h;                 /* sprite dims */"
    echo "    unsigned char missing;      /* 1 = reuse previous frame's CEL */"
    echo "    const unsigned char *mask;  /* (w*h+7)/8 bytes, bit-packed 1bpp (set=opaque) — sessione 6 */"
    echo "} ${NAME}_frame_t;"
    echo ""

    # per-frame hitmask arrays — bit-packed 1 bpp, same encoding as run_pipeline_all.sh.
    while read -r mfline; do
        case "$mfline" in '#'*|'') continue ;; esac
        read -r idx fn w h px py missing <<<"$mfline"
        [ "$missing" = "1" ] && continue
        mask_file="$STAGE_DIR/frame_$(printf "%02d" "$idx").mask"
        [ -f "$mask_file" ] || continue
        echo "static const unsigned char ${NAME}_frame${idx}_mask[] = {"
        od -An -vtu1 -w16 "$mask_file" | awk '{
            for (i=1; i<=NF; i++) printf "%s,", $i;
            printf "\n";
        }' | sed 's/^/    /'
        echo "};"
    done < "$STAGE_DIR/manifest.txt"

    echo "static const ${NAME}_frame_t ${NAME}_frames[] = {"
    while read -r line; do
        case "$line" in '#'*|'') continue ;; esac
        read -r idx fn w h px py missing <<<"$line"
        if [ "$missing" = "1" ]; then
            echo "    { (const char *)0, $px, $py, $w, $h, 1, (const unsigned char *)0 },"
        else
            cel_base=$(basename "$fn" .png)
            mask_file="$STAGE_DIR/frame_$(printf "%02d" "$idx").mask"
            if [ -f "$mask_file" ]; then
                mask_ref="${NAME}_frame${idx}_mask"
            else
                mask_ref="(const unsigned char *)0"
            fi
            echo "    { \"Art/HAR_${NAME_UPPER}/${cel_base}.CEL\", $px, $py, $w, $h, 0, $mask_ref },"
        fi
    done < "$STAGE_DIR/manifest.txt"
    echo "};"
    echo "#define ${NAME_UPPER}_FRAME_COUNT (sizeof(${NAME}_frames)/sizeof(${NAME}_frames[0]))"
    echo ""
    echo "#endif"
} > "$HEADER"

echo "Pipeline OK. Inspect:"
echo "  $CEL_DIR/"
echo "  $HEADER"
