#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_intro.sh — extract READY + FIGHT sprites from ARENA0.BK
# (anim[11] + anim[10]) and FIGHT announcer voice from SOUNDS.DAT[10]
# (resolved via ARENA0 stl: s11 -> stl[11]=11 -> SOUNDS.DAT id 11, 0-idx 10).
#
# Canon (openomf-master src/game/scenes/arena.c L417-451):
#   - round 1: ARENA.BK anim[11] READY (silent in stl) -> 10-tick gap
#              -> anim[10] FIGHT (s11sp22 triggers SOUNDS.DAT[10])
# Other arena BKs share the same stl[11]=11 mapping, so a single CEL +
# AIFF works for all 5 arenas (sessione 10.6 minimal scope).
#
# Usage: ./run_pipeline_intro.sh

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_BK="$SCRIPT_DIR/build/dump_bk_bg"
DUMP_HAR="$SCRIPT_DIR/build/dump_har"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

BK="${OMF_DATA}/ARENA0.BK"
SND="${OMF_DATA}/SOUNDS.DAT"
CEL_OUT_DIR="$PROJ_ROOT/takeme/Art/INTRO"
AUDIO_OUT_DIR="$PROJ_ROOT/takeme/Audio/INTRO"
STAGE_READY="/tmp/intro_ready_stage"
STAGE_FIGHT="/tmp/intro_fight_stage"
STAGE_AUDIO="/tmp/intro_audio_stage"
HEADER_OUT="$PROJ_ROOT/src/intro_data.h"

# Canon stl mapping (verified via dump_bk_bg info):
#   FIGHT anim_string s11 -> ARENA*.BK stl[11] = 11 -> SOUNDS.DAT[10] (0-indexed)
FIGHT_SOUND_ID=11   # 1-indexed for SOUNDS.DAT (matches dump_har convention)

rm -rf "$STAGE_READY" "$STAGE_FIGHT" "$STAGE_AUDIO" "$CEL_OUT_DIR" "$AUDIO_OUT_DIR"
mkdir -p "$STAGE_READY" "$STAGE_FIGHT" "$STAGE_AUDIO" "$CEL_OUT_DIR" "$AUDIO_OUT_DIR"

echo "[1/4] dump anim[11] READY -> $STAGE_READY"
"$DUMP_BK" dump-anim "$BK" 11 "$STAGE_READY" > /dev/null \
    || { echo "READY dump FAILED"; exit 1; }

echo "[2/4] dump anim[10] FIGHT -> $STAGE_FIGHT"
"$DUMP_BK" dump-anim "$BK" 10 "$STAGE_FIGHT" > /dev/null \
    || { echo "FIGHT dump FAILED"; exit 1; }

echo "[3/4] 3it to-cel READY + FIGHT"
for src in "$STAGE_READY/sprite_00.png:$CEL_OUT_DIR/READY.CEL" \
           "$STAGE_FIGHT/sprite_00.png:$CEL_OUT_DIR/FIGHT.CEL"; do
    in_png="${src%:*}"
    out_cel="${src#*:}"
    if [ ! -f "$in_png" ]; then echo "  missing $in_png"; continue; fi
    "$THREE_IT" to-cel --find-smallest regular --output-path "$out_cel" "$in_png" \
        > /dev/null 2>&1 \
        && echo "  $(basename "$out_cel") ($(stat -c%s "$out_cel") bytes)" \
        || { echo "  3it FAILED on $in_png"; exit 1; }
done

echo "[4/4] extract SOUNDS.DAT[id=$FIGHT_SOUND_ID] (FIGHT voice)"
"$DUMP_HAR" sound "$SND" "$STAGE_AUDIO" $FIGHT_SOUND_ID \
    || { echo "sound extract FAILED"; exit 1; }

aiff_src="$STAGE_AUDIO/sfx_$(printf '%03d' $FIGHT_SOUND_ID).aiff"
aiff_dst="$AUDIO_OUT_DIR/FIGHT.aiff"
cp "$aiff_src" "$aiff_dst" || { echo "cp $aiff_src FAILED"; exit 1; }
echo "  copied -> $aiff_dst ($(stat -c%s "$aiff_dst") bytes)"

# Read manifest for sprite dimensions/anchor
read_mf() {
    local mf="$1/manifest.txt"
    awk '/^0 sprite/ { print $3, $4, $5, $6 }' "$mf"
}
read_ready=$(read_mf "$STAGE_READY")
read_fight=$(read_mf "$STAGE_FIGHT")
# format: w h pos_x pos_y
set -- $read_ready
ready_w="$1"; ready_h="$2"; ready_px="$3"; ready_py="$4"
set -- $read_fight
fight_w="$1"; fight_h="$2"; fight_px="$3"; fight_py="$4"

echo "Emit $HEADER_OUT"
cat > "$HEADER_OUT" <<EOF
/* Auto-generated by port_3do/host_tools/run_pipeline_intro.sh -- do NOT edit. */
/* READY/FIGHT intro sprites from ARENA0.BK + FIGHT announcer voice from SOUNDS.DAT[id=$FIGHT_SOUND_ID]. */
#ifndef INTRO_DATA_H
#define INTRO_DATA_H

/* Sprite anchor convention: drawn at (INTRO_ANCHOR_X + pos_x, INTRO_ANCHOR_Y + pos_y).
 * Canon start_pos=(160,100) per dump_bk_bg info, but our scene anchors at
 * screen center with the canon offsets baked in to compensate. */
#define INTRO_ANCHOR_X   160
#define INTRO_ANCHOR_Y   100

#define INTRO_READY_CEL  "Art/INTRO/READY.CEL"
#define INTRO_READY_W    $ready_w
#define INTRO_READY_H    $ready_h
#define INTRO_READY_PX   ($ready_px)
#define INTRO_READY_PY   ($ready_py)

#define INTRO_FIGHT_CEL  "Art/INTRO/FIGHT.CEL"
#define INTRO_FIGHT_W    $fight_w
#define INTRO_FIGHT_H    $fight_h
#define INTRO_FIGHT_PX   ($fight_px)
#define INTRO_FIGHT_PY   ($fight_py)

#define INTRO_FIGHT_AIFF "Audio/INTRO/FIGHT.aiff"

/* Canon timing (arena.c L191): READY anim (~33 ticks) + 10-tick gap + FIGHT anim (~33 ticks).
 * At 60Hz screen we use a tighter mapping for snappy gameplay onset. */
#define INTRO_READY_TICKS  60    /* ~1 sec READY hold */
#define INTRO_GAP_TICKS    10    /* ~0.17 sec gap   */
#define INTRO_FIGHT_TICKS  60    /* ~1 sec FIGHT hold */

#endif /* INTRO_DATA_H */
EOF

echo "Pipeline OK."
