#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_har_idles.sh — extract IDLE animation (move 11 = ANIM_IDLE
# per openomf-master src/resources/animation.h) from all 10 playable
# HARs (FIGHTR0..9.AF) as CELs, emit one consolidated data header.
#
# Used by scene_select.c to play the cursored HAR's idle preview next to
# the selected pilot's portrait (sessione 10.5 parity feature).
# Per-pilot palette is NOT applied -- previews show the "naked" HAR
# colors (matches OMF DOS HAR-select behavior).
#
# Usage:
#   ./run_pipeline_har_idles.sh

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_HAR="$SCRIPT_DIR/build/dump_har"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

AF_DIR="${OMF_DATA}"
BK="$AF_DIR/ARENA0.BK"           # any arena palette works -- HAR sprites use shared base palette region
HEADER_OUT="$PROJ_ROOT/src/har_idles_data.h"
CEL_BASE="$PROJ_ROOT/takeme/Art/IDLES"

NAMES=("jaguar" "shadow" "thorn" "katana" "shredder" "flail" "gargoyle" "chronos" "pyros" "electra")
NUM_HARS=${#NAMES[@]}

IDLE_MOVE=11

rm -rf "$CEL_BASE"
mkdir -p "$CEL_BASE"

total_cels=0
total_bytes=0

# Pass 1: extract + convert
for i in $(seq 0 $((NUM_HARS - 1))); do
    name="${NAMES[$i]}"
    af="$AF_DIR/FIGHTR${i}.AF"
    stage="/tmp/idle_${name}_stage"
    out_dir="$CEL_BASE/har_$(printf '%02d' $i)"

    rm -rf "$stage"
    mkdir -p "$stage" "$out_dir"

    "$DUMP_HAR" dump "$af" "$BK" $IDLE_MOVE "$stage" > /dev/null 2>&1 \
        || { echo "  $name: dump_har FAILED"; continue; }

    cels=0; bytes=0
    for png in "$stage"/frame_*.png; do
        [ -f "$png" ] || continue
        base=$(basename "$png" .png)
        out="$out_dir/$base.CEL"
        "$THREE_IT" to-cel --find-smallest regular --output-path "$out" "$png" \
            > /dev/null 2>&1 \
            || { echo "  $name: 3it FAILED on $png"; continue; }
        cels=$((cels + 1))
        bytes=$((bytes + $(stat -c%s "$out")))
    done
    printf "  har_%02d %-10s frames=%d size=%d B\n" "$i" "$name" "$cels" "$bytes"
    total_cels=$((total_cels + cels))
    total_bytes=$((total_bytes + bytes))
done
echo "Total: $total_cels CELs, $((total_bytes / 1024)) KB on ISO"

# Pass 2: emit consolidated header.
{
    cat <<'EOF'
/* Auto-generated by port_3do/host_tools/run_pipeline_har_idles.sh -- do NOT edit. */
/* IDLE animations (move 11 = ANIM_IDLE) for all 10 OMF HARs, used by
 * scene_select.c to preview the cursored HAR next to the selected pilot. */
#ifndef HAR_IDLES_DATA_H
#define HAR_IDLES_DATA_H

typedef struct {
    const char *cel_path;
    short pos_x, pos_y;     /* OMF anchor offset (sprite top-left = obj_pos + pos) */
    short w, h;
} idle_frame_t;

typedef struct {
    short sprite_idx;       /* 0..frame_count-1 */
    short dwell_ticks;      /* OMF ticks at canon 60fps; runtime can scale */
} idle_step_t;

typedef struct {
    const char         *name;            /* debug-friendly HAR name */
    short               frame_count;
    short               step_count;
    const idle_frame_t *frames;
    const idle_step_t  *steps;
} idle_har_t;

EOF

    # Per-HAR frame + step arrays
    for i in $(seq 0 $((NUM_HARS - 1))); do
        name="${NAMES[$i]}"
        stage="/tmp/idle_${name}_stage"
        ipad=$(printf '%02d' $i)
        manifest="$stage/manifest.txt"
        steps="$stage/steps.txt"

        [ -f "$manifest" ] || { echo "/* har_$ipad $name: no manifest -- skipped */"; continue; }

        # frames[]
        printf "static const idle_frame_t har_%s_idle_frames[] = {\n" "$ipad"
        while read -r ln; do
            case "$ln" in '#'*|'') continue ;; esac
            read -r fr_idx fn w h px py missing <<<"$ln"
            if [ "$missing" = "1" ]; then
                # idle never has missing frames in practice; emit a 1x1 placeholder
                printf "    { (const char *)0, %s, %s, 1, 1 },\n" "$px" "$py"
            else
                cel_base=$(basename "$fn" .png)
                printf "    { \"Art/IDLES/har_%s/%s.CEL\", %s, %s, %s, %s },\n" \
                       "$ipad" "$cel_base" "$px" "$py" "$w" "$h"
            fi
        done < "$manifest"
        printf "};\n"

        # steps[]
        printf "static const idle_step_t har_%s_idle_steps[] = {\n" "$ipad"
        step_n=0
        if [ -f "$steps" ]; then
            while read -r ln; do
                case "$ln" in '#'*|'') continue ;; esac
                read -r idx sprite dwell rest <<<"$ln"
                printf "    { %s, %s },\n" "$sprite" "$dwell"
                step_n=$((step_n + 1))
            done < "$steps"
        fi
        if [ "$step_n" = "0" ]; then
            printf "    { 0, 6 },  /* placeholder -- never read at runtime */\n"
        fi
        printf "};\n"
        printf "#define HAR_%s_IDLE_STEP_COUNT (%d)\n\n" "$ipad" "$step_n"
    done

    # Master table
    printf "static const idle_har_t har_idles[] = {\n"
    for i in $(seq 0 $((NUM_HARS - 1))); do
        name="${NAMES[$i]}"
        ipad=$(printf '%02d' $i)
        stage="/tmp/idle_${name}_stage"
        manifest="$stage/manifest.txt"
        if [ ! -f "$manifest" ]; then
            printf "    { \"%s\", 0, 0, (const idle_frame_t *)0, (const idle_step_t *)0 },\n" "$name"
            continue
        fi
        frame_n=$(grep -cv '^#' "$manifest" | head -1 || echo 0)
        # awk because some lines are blank
        frame_n=$(awk '!/^#/ && NF>0 {n++} END{print n+0}' "$manifest")
        steps="$stage/steps.txt"
        step_n=0
        [ -f "$steps" ] && step_n=$(awk '!/^#/ && NF>0 {n++} END{print n+0}' "$steps")
        printf "    { \"%s\", %d, %d, har_%s_idle_frames, har_%s_idle_steps },\n" \
               "$name" "$frame_n" "$step_n" "$ipad" "$ipad"
    done
    printf "};\n"
    printf "#define HAR_IDLES_COUNT (sizeof(har_idles) / sizeof(har_idles[0]))\n\n"
    printf "#endif /* HAR_IDLES_DATA_H */\n"
} > "$HEADER_OUT"

echo "Header written -> $HEADER_OUT"
