#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_vs_har_sheet.sh — extract VS.BK anim[5] sprites (11 HAR
# pose stills, one per HAR in OMF: Jaguar=0..Nova=10) as 3DO CELs +
# emit a data header for the runtime.
#
# Drawn at canon position (160, 0) in scene_vs.c. The 12th sprite from
# the BK dump is a 1×1 placeholder and is intentionally skipped.
#
# Usage:
#   ./run_pipeline_vs_har_sheet.sh

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_BK="$SCRIPT_DIR/build/dump_bk_bg"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

BK="${OMF_DATA}/VS.BK"
STAGE_DIR="/tmp/vs_anim5_stage"
CEL_OUT_DIR="$PROJ_ROOT/takeme/Art/VS_HARS"
HEADER_OUT="$PROJ_ROOT/src/vs_har_sheet_data.h"

NUM_HARS=11      # OMF has 11 HAR sprites in VS.BK anim[5]; index 11 is a 1×1 dummy.
NUM_PILOTS=10    # CRYSTAL..RAVEN; KREISSACK boss is index 10 (no per-pilot variant for now).
P2_PAL_OFFSET=48 # canon vs.c L575: object_set_pal_offset(player2_har, 48)

rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR" "$CEL_OUT_DIR"

# Stage all P2 per-pilot dirs.
for p in $(seq 0 $((NUM_PILOTS - 1))); do
    mkdir -p "/tmp/vs_anim5_p2_${p}_stage" "$PROJ_ROOT/takeme/Art/VS_HARS_P2_${p}"
done

echo "[1/4] dump_bk_bg dump-anim $BK 5 (P1, palette[0..15]) -> $STAGE_DIR"
"$DUMP_BK" dump-anim "$BK" 5 "$STAGE_DIR" > /dev/null \
    || { echo "dump-anim P1 FAILED"; exit 1; }

echo "[2/4] dump_bk_bg dump-anim x$NUM_PILOTS (P2 +offset=$P2_PAL_OFFSET +inject_pilot per pilot)"
for p in $(seq 0 $((NUM_PILOTS - 1))); do
    "$DUMP_BK" dump-anim "$BK" 5 "/tmp/vs_anim5_p2_${p}_stage" \
        $P2_PAL_OFFSET $p > /dev/null \
        || { echo "dump-anim P2 pilot=$p FAILED"; exit 1; }
done

echo "[3/4] 3it to-cel x$NUM_HARS x$((NUM_PILOTS + 1)) (P1 + 10 P2 sets)"
for i in $(seq 0 $((NUM_HARS - 1))); do
    n=$(printf "%02d" "$i")
    # P1 (canon palette)
    png="$STAGE_DIR/sprite_$n.png"
    cel="$CEL_OUT_DIR/har_$n.CEL"
    if [ -f "$png" ]; then
        "$THREE_IT" to-cel --find-smallest regular --output-path "$cel" "$png" \
            > /dev/null 2>&1 \
            || { echo "  3it P1 FAILED on $png"; exit 1; }
    fi
    # P2 per-pilot
    for p in $(seq 0 $((NUM_PILOTS - 1))); do
        png="/tmp/vs_anim5_p2_${p}_stage/sprite_$n.png"
        cel="$PROJ_ROOT/takeme/Art/VS_HARS_P2_${p}/har_$n.CEL"
        if [ ! -f "$png" ]; then continue; fi
        "$THREE_IT" to-cel --find-smallest regular --output-path "$cel" "$png" \
            > /dev/null 2>&1 \
            || { echo "  3it P2 pilot=$p FAILED on $png"; exit 1; }
    done
    p1sz=$(stat -c%s "$CEL_OUT_DIR/har_$n.CEL" 2>/dev/null)
    p2sz=$(stat -c%s "$PROJ_ROOT/takeme/Art/VS_HARS_P2_5/har_$n.CEL" 2>/dev/null)
    printf "  har_%s (P1=%s B, P2[JEANPAUL]=%s B)\n" "$n" "$p1sz" "$p2sz"
done

echo "[4/4] emit $HEADER_OUT"
{
    cat <<'EOF'
/* Auto-generated by port_3do/host_tools/run_pipeline_vs_har_sheet.sh
 * -- do NOT edit. Source: ${OMF_DATA}/VS.BK anim[5] (11 HAR sprites). */
#ifndef VS_HAR_SHEET_DATA_H
#define VS_HAR_SHEET_DATA_H

typedef struct {
    int         w, h;          /* sprite pixel dims */
    int         pos_x, pos_y;  /* OMF anchor offset (sprite top-left = obj_pos + (pos_x, pos_y)) */
    const char *cel_path_p1;       /* P1 CEL (canon palette[0..15]) */
    const char *cel_path_p2[10];   /* P2 CEL per opponent pilot 0..9 (canon altpal injected) */
} vs_har_sprite_t;

#define VS_HAR_P2_PILOT_COUNT 10

/* HAR sprites for the VS pre-fight, drawn at canon object position
 * (160, 0). Index = OMF har_id (JAGUAR=0, SHADOW=1, THORN=2, ...).
 * cel_path_p2[pilot_idx] is the per-pilot canon recolor (palette[49..95]
 * loaded with pilot->altpal[c1/c2/c3], then +48 shift). */
static const vs_har_sprite_t vs_har_sheet[] = {
EOF
    for i in $(seq 0 $((NUM_HARS - 1))); do
        n=$(printf "%02d" "$i")
        manifest_line=$(awk -v idx="$i" '$1 == idx { print; exit }' "$STAGE_DIR/manifest.txt")
        if [ -z "$manifest_line" ]; then continue; fi
        # manifest line: idx filename w h pos_x pos_y
        w=$(echo "$manifest_line" | awk '{print $3}')
        h=$(echo "$manifest_line" | awk '{print $4}')
        px=$(echo "$manifest_line" | awk '{print $5}')
        py=$(echo "$manifest_line" | awk '{print $6}')
        printf "    { %3d, %3d, %4d, %3d,\n        \"Art/VS_HARS/har_%s.CEL\",\n        {\n" \
               "$w" "$h" "$px" "$py" "$n"
        for p in $(seq 0 $((NUM_PILOTS - 1))); do
            printf "            \"Art/VS_HARS_P2_%s/har_%s.CEL\",\n" "$p" "$n"
        done
        printf "        }\n    },\n"
    done
    cat <<'EOF'
};

#define VS_HAR_SHEET_COUNT  (sizeof(vs_har_sheet) / sizeof(vs_har_sheet[0]))

#endif /* VS_HAR_SHEET_DATA_H */
EOF
} > "$HEADER_OUT"

echo "Pipeline OK -- $HEADER_OUT written."
