#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_pilots.sh -- OMF pilot color extraction.
#
# Steps:
#   1. dump_altpals     -> 10 swatch PNGs (24x8 each) + manifest in stage
#   2. 3it to-cel       -> 10 swatch CELs in takeme/Art/PILOTS/
#   3. C header gen     -> src/pilots_data.h with name + color indices +
#                          swatch CEL path per pilot
#
# Sessione 7 final polish: proves both pilot select + the OMF altpal
# layer end-to-end (per [[project-har-palette-remap]]).

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP="$SCRIPT_DIR/build/dump_altpals"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

ALTPALS="${1:-${OMF_DATA}/ALTPALS.DAT}"
STAGE_DIR="/tmp/pilots_stage"
CEL_DIR="$PROJ_ROOT/takeme/Art/PILOTS"
HEADER="$PROJ_ROOT/src/pilots_data.h"

if [ ! -x "$DUMP" ]; then
    echo "dump_altpals not built; run 'make build/dump_altpals' first." >&2
    exit 1
fi

rm -rf "$STAGE_DIR" "$CEL_DIR"
mkdir -p "$STAGE_DIR" "$CEL_DIR"

echo "[1/3] dump_altpals $ALTPALS -> $STAGE_DIR"
"$DUMP" dump "$ALTPALS" "$STAGE_DIR" || { echo "dump_altpals failed"; exit 1; }

echo "[2/3] 3it to-cel -> $CEL_DIR"
ok=0
for png in "$STAGE_DIR"/pilot_*_swatch.png; do
    [ -f "$png" ] || continue
    base=$(basename "$png" .png)
    out="$CEL_DIR/${base}.CEL"
    "$THREE_IT" to-cel --find-smallest regular --output-path "$out" "$png" \
            > /dev/null 2>&1 && ok=$((ok + 1)) || \
        echo "  3it failed on $png"
done
echo "  $ok swatch CELs written"

echo "[3/3] write C header -> $HEADER"
{
    echo "/* Auto-generated by port_3do/host_tools/run_pipeline_pilots.sh -- do NOT edit. */"
    echo "/* source: $ALTPALS */"
    echo "#ifndef PILOTS_DATA_H"
    echo "#define PILOTS_DATA_H"
    echo ""
    echo "typedef struct {"
    echo "    int         id;            /* matches openomf PILOT_* enum (common_defines.h:78-94) */"
    echo "    const char *name;          /* uppercase canon name */"
    echo "    unsigned char color_1;     /* primary HAR color altpal slot (0..15) */"
    echo "    unsigned char color_2;     /* secondary */"
    echo "    unsigned char color_3;     /* tertiary */"
    echo "    const char *swatch_cel;    /* 3DO filesystem path */"
    echo "} pilot_data_t;"
    echo ""
    echo "static const pilot_data_t pilots_data[] = {"
    while read -r line; do
        case "$line" in '#'*|'') continue ;; esac
        read -r id name c1 c2 c3 png <<<"$line"
        cel_base=$(basename "$png" .png)
        echo "    { $id, \"$name\", $c1, $c2, $c3, \"Art/PILOTS/${cel_base}.CEL\" },"
    done < "$STAGE_DIR/manifest.txt"
    echo "};"
    echo "#define PILOTS_COUNT  (sizeof(pilots_data) / sizeof(pilots_data[0]))"
    echo ""
    echo "#endif /* PILOTS_DATA_H */"
} > "$HEADER"

echo "Pipeline OK."
echo "  $CEL_DIR/"
echo "  $HEADER"
