#!/usr/bin/env bash
: "${OMF_DATA:?set OMF_DATA to your OMF:2097 data directory (e.g. export OMF_DATA=/path/to/OMF)}"
#
# run_pipeline_all.sh — dump ALL moves of a HAR + convert all sprites to CEL
# + dump SOUNDS.DAT entries referenced by this HAR to AIFF + emit a consolidated
# C header with one frames[] AND one steps[] array per move, a master moves[]
# index table, and an sfx[] index table.
#
# The runtime side just consumes structs — no anim-string parsing at runtime.
#
# Usage:
#   ./run_pipeline_all.sh <har_name> <FIGHTRn.AF> <ARENAm.BK> [SOUNDS.DAT]
# Example:
#   ./run_pipeline_all.sh jaguar ${OMF_DATA}/FIGHTR0.AF ${OMF_DATA}/ARENA0.BK \
#                          ${OMF_DATA}/SOUNDS.DAT

set -u

if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
    echo "Usage: $0 <har_name> <AF_file> <BK_file> [SOUNDS.DAT]"
    exit 1
fi

NAME="$1"
AF="$2"
BK="$3"
SND="${4:-}"
NAME_UPPER=$(echo "$NAME" | tr '[:lower:]' '[:upper:]')

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DUMP_HAR="$SCRIPT_DIR/build/dump_har"
THREE_IT="$HOME/3do-devkit/bin/tools/linux/3it"

STAGE_DIR="/tmp/${NAME}_all_stage"
ART_DIR="$PROJ_ROOT/takeme/Art/HAR_${NAME_UPPER}"
SFX_STAGE="/tmp/${NAME}_sfx_stage"
SFX_DIR="$PROJ_ROOT/takeme/Audio/HAR_${NAME_UPPER}"
HEADER="$PROJ_ROOT/src/${NAME}_all_data.h"

rm -rf "$STAGE_DIR" "$ART_DIR" "$SFX_STAGE" "$SFX_DIR"
mkdir -p "$STAGE_DIR" "$ART_DIR"

echo "[1/4] dump-all $AF $BK -> $STAGE_DIR"
"$DUMP_HAR" dump-all "$AF" "$BK" "$STAGE_DIR" > /dev/null || {
    echo "dump-all failed"; exit 1;
}
n_moves=$(grep -c '^[0-9]' "$STAGE_DIR/index.txt" || echo 0)
echo "  dumped $n_moves moves"

echo "[2/4] convert PNGs to CELs -> $ART_DIR"
total_cels=0
total_bytes=0
while read -r line; do
    case "$line" in '#'*|'') continue ;; esac
    read -r move_id cat sprite_count mstring rest <<<"$line"
    mv_pad=$(printf "%02d" "$move_id")
    out_dir="$ART_DIR/move_$mv_pad"
    mkdir -p "$out_dir"
    for png in "$STAGE_DIR/move_$mv_pad"/frame_*.png; do
        [ -f "$png" ] || continue
        base=$(basename "$png" .png)
        out="$out_dir/${base}.CEL"
        "$THREE_IT" to-cel --find-smallest regular --output-path "$out" "$png" > /dev/null 2>&1 || {
            echo "  3it failed on $png"; continue;
        }
        total_cels=$((total_cels + 1))
        total_bytes=$((total_bytes + $(stat -c%s "$out")))
    done
done < "$STAGE_DIR/index.txt"
echo "  converted $total_cels CELs, total $((total_bytes / 1024)) KB"

# Step 3 is optional — only if SOUNDS.DAT was provided.
sfx_count=0
if [ -n "$SND" ]; then
    echo "[3/4] dump SOUNDS.DAT -> $SFX_STAGE then copy to $SFX_DIR"
    mkdir -p "$SFX_STAGE" "$SFX_DIR"
    "$DUMP_HAR" sounds "$SND" "$AF" "$SFX_STAGE" > /dev/null || {
        echo "  sounds dump failed"; exit 1;
    }
    cp "$SFX_STAGE"/*.aiff "$SFX_DIR"/ 2>/dev/null || true
    sfx_count=$(ls "$SFX_DIR"/*.aiff 2>/dev/null | wc -l)
    sfx_bytes=$(du -sb "$SFX_DIR" 2>/dev/null | awk '{print $1}')
    echo "  copied $sfx_count AIFF samples, total $((sfx_bytes / 1024)) KB"
else
    echo "[3/4] skipped (no SOUNDS.DAT path provided)"
fi

echo "[4/4] write C header -> $HEADER"
{
    echo "/* Auto-generated by port_3do/host_tools/run_pipeline_all.sh -- do NOT edit. */"
    echo "/* HAR=$NAME  AF=$AF  BK=$BK  SOUNDS=${SND:-<none>} */"
    echo "#ifndef ${NAME_UPPER}_ALL_DATA_H"
    echo "#define ${NAME_UPPER}_ALL_DATA_H"
    echo ""

    # Per-HAR base health + endurance (parsed from the AF_INFO header line
    # written by dump_har dump-all). Emitted as #defines so the runtime can
    # pick them up at compile time via gCurHarPack->base_health.
    af_info_line=$(grep '^# AF_INFO' "$STAGE_DIR/index.txt" | head -1)
    base_health=$(echo "$af_info_line" | sed -n 's/.*health=\([0-9]*\).*/\1/p')
    base_end_x1000=$(echo "$af_info_line" | sed -n 's/.*endurance_x1000=\(-\{0,1\}[0-9]*\).*/\1/p')
    : "${base_health:=0}"
    : "${base_end_x1000:=0}"
    echo "#define ${NAME_UPPER}_BASE_HEALTH        ($base_health)"
    echo "#define ${NAME_UPPER}_BASE_ENDURANCE_X1000 ($base_end_x1000)"
    echo ""
    echo "typedef struct {"
    echo "    const char *cel_path;"
    echo "    short pos_x, pos_y;"
    echo "    short w, h;"
    echo "    unsigned char missing;"
    echo "    const unsigned char *mask;  /* (w*h+7)/8 bytes, bit-packed 1bpp (set=opaque) — sessione 6 */"
    echo "} ${NAME}_frame_t;"
    echo ""
    echo "typedef struct {"
    echo "    short sprite_idx;        /* 0..25  (= letter - 'A') */"
    echo "    short dwell_ticks;       /* OMF ticks */"
    echo "    short sound_param;       /* AF soundtable index 0..29; -1 = none */"
    echo "    short sound_freq_pitch;  /* -128..128; 0 = use AIFF native freq */"
    echo "    short sound_vol;         /* 0..63; -1 = default */"
    echo "    short sound_pan;         /* -100..100; -127 = auto-pan */"
    echo "    unsigned char flip_r;    /* horizontal flip this frame */"
    echo "    unsigned char flip_f;    /* vertical flip this frame */"
    echo "} ${NAME}_anim_step_t;"
    echo ""
    echo "/* Layout-compatible with openomf_shim/resources/animation.h collision_coord."
    echo " * Cast to (const collision_coord *) and wrap via shim_vector_view to feed"
    echo " * intersect_har_sprite_hitpoint. Three ints = 12 bytes per entry. */"
    echo "typedef struct {"
    echo "    int x;"
    echo "    int y;"
    echo "    int frame_index;"
    echo "} ${NAME}_coord_t;"
    echo ""

    # Pass 1: emit one frames[] AND one steps[] array per move
    while read -r line; do
        case "$line" in '#'*|'') continue ;; esac
        read -r move_id cat sprite_count damage mstring rest <<<"$line"
        mv_pad=$(printf "%02d" "$move_id")
        manifest="$STAGE_DIR/move_$mv_pad/manifest.txt"
        steps_txt="$STAGE_DIR/move_$mv_pad/steps.txt"

        # per-frame hitmask byte arrays (emitted before frames[] so frames[] can
        # reference them). Each .mask file is a bit-packed (w*h+7)/8 binary
        # blob (1 bpp, set=opaque) — see dump_har.c dump_move_inner.
        while read -r mfline; do
            case "$mfline" in '#'*|'') continue ;; esac
            read -r idx fn w h px py missing <<<"$mfline"
            [ "$missing" = "1" ] && continue
            mask_file="$STAGE_DIR/move_$mv_pad/frame_$(printf "%02d" "$idx").mask"
            [ -f "$mask_file" ] || continue
            echo "static const unsigned char ${NAME}_move${mv_pad}_frame${idx}_mask[] = {"
            # Convert binary to comma-separated hex on lines of 16 bytes.
            # od -An -vtu1 -w16 prints 16 unsigned decimals per line; sed wraps
            # them with commas + brace formatting.
            od -An -vtu1 -w16 "$mask_file" | awk '{
                for (i=1; i<=NF; i++) printf "%s,", $i;
                printf "\n";
            }' | sed 's/^/    /'
            echo "};"
        done < "$manifest"

        # frames[] — now with mask pointer field
        echo "static const ${NAME}_frame_t ${NAME}_move${mv_pad}_frames[] = {"
        while read -r mfline; do
            case "$mfline" in '#'*|'') continue ;; esac
            read -r idx fn w h px py missing <<<"$mfline"
            if [ "$missing" = "1" ]; then
                echo "    { (const char *)0, $px, $py, $w, $h, 1, (const unsigned char *)0 },"
            else
                cel_base=$(basename "$fn" .png)
                mask_file="$STAGE_DIR/move_$mv_pad/frame_$(printf "%02d" "$idx").mask"
                if [ -f "$mask_file" ]; then
                    mask_ref="${NAME}_move${mv_pad}_frame${idx}_mask"
                else
                    mask_ref="(const unsigned char *)0"
                fi
                echo "    { \"Art/HAR_${NAME_UPPER}/move_${mv_pad}/${cel_base}.CEL\", $px, $py, $w, $h, 0, $mask_ref },"
            fi
        done < "$manifest"
        echo "};"

        # coords[] — collision coordinates for this move.
        # ARM SDT 2.51 rejects zero-element static arrays; emit a sentinel
        # entry when this move has no coords. The runtime gates on
        # move->coord_count, so the sentinel is never read.
        coords_txt="$STAGE_DIR/move_$mv_pad/coords.txt"
        coord_n=0
        echo "static const ${NAME}_coord_t ${NAME}_move${mv_pad}_coords[] = {"
        if [ -f "$coords_txt" ]; then
            while read -r ccline; do
                case "$ccline" in '#'*|'') continue ;; esac
                read -r cfi cx cy <<<"$ccline"
                echo "    { $cx, $cy, $cfi },"
                coord_n=$((coord_n + 1))
            done < "$coords_txt"
        fi
        if [ "$coord_n" = "0" ]; then
            echo "    { 0, 0, 0 },  /* sentinel - never read at runtime (coord_count==0) */"
        fi
        echo "};"
        echo "#define ${NAME_UPPER}_MOVE${mv_pad}_COORD_COUNT ($coord_n)"

        # steps[]
        echo "static const ${NAME}_anim_step_t ${NAME}_move${mv_pad}_steps[] = {"
        step_n=0
        if [ -f "$steps_txt" ]; then
            while read -r stline; do
                case "$stline" in '#'*|'') continue ;; esac
                read -r idx sprite dwell s_param s_freq s_vol s_pan r f <<<"$stline"
                echo "    { $sprite, $dwell, $s_param, $s_freq, $s_vol, $s_pan, $r, $f },"
                step_n=$((step_n + 1))
            done < "$steps_txt"
        fi
        echo "};"
        echo "#define ${NAME_UPPER}_MOVE${mv_pad}_STEP_COUNT ($step_n)"
        echo ""
    done < "$STAGE_DIR/index.txt"

    # Pass 2: master moves[] table
    echo "typedef struct {"
    echo "    short id;                 /* original OMF move ID 1..69 */"
    echo "    short frame_count;"
    echo "    short category;"
    echo "    short step_count;"
    echo "    short coord_count;        /* collision_coord entries in coords[] */"
    echo "    short damage;             /* OMF move.damage_amount 0..255 — sessione 9 */"
    echo "    const ${NAME}_frame_t *frames;"
    echo "    const ${NAME}_anim_step_t *steps;"
    echo "    const ${NAME}_coord_t *coords;   /* may be NULL if coord_count==0 */"
    echo "    const char *input;        /* OMF move_string ('P','K','P2',...); NULL if non-matchable */"
    echo "    const char *anim_string;  /* kept for debug printing */"
    echo "} ${NAME}_move_t;"
    echo ""
    echo "static const ${NAME}_move_t ${NAME}_moves[] = {"
    n=0
    while read -r line; do
        case "$line" in '#'*|'') continue ;; esac
        read -r move_id cat sprite_count damage mstring rest <<<"$line"
        mv_pad=$(printf "%02d" "$move_id")
        # Recount steps for this move from steps.txt (skip comment lines).
        steps_txt="$STAGE_DIR/move_$mv_pad/steps.txt"
        if [ -f "$steps_txt" ]; then
            step_n=$(grep -cv '^#' "$steps_txt")
        else
            step_n=0
        fi
        coords_txt="$STAGE_DIR/move_$mv_pad/coords.txt"
        if [ -f "$coords_txt" ]; then
            coord_n=$(grep -cv '^#' "$coords_txt")
        else
            coord_n=0
        fi
        esc=$(echo "$rest" | sed 's/\\/\\\\/g; s/"/\\"/g')
        if [ "$mstring" = "-" ]; then
            input_field="(const char *)0"
        else
            mstring_esc=$(echo "$mstring" | sed 's/\\/\\\\/g; s/"/\\"/g')
            input_field="\"$mstring_esc\""
        fi
        echo "    { $move_id, $sprite_count, $cat, $step_n, $coord_n, $damage, ${NAME}_move${mv_pad}_frames, ${NAME}_move${mv_pad}_steps, ${NAME}_move${mv_pad}_coords, $input_field, \"$esc\" },"
        n=$((n + 1))
    done < "$STAGE_DIR/index.txt"
    echo "};"
    echo "#define ${NAME_UPPER}_MOVES_COUNT ($n)"
    echo ""

    # Pass 3: sfx[] table — direct-indexed by AF soundtable param (0..29).
    echo "typedef struct {"
    echo "    short sound_id;          /* SOUNDS.DAT id 1..299; 0 = unused slot */"
    echo "    int   freq_hz;           /* native AIFF sample rate */"
    echo "    const char *aiff_path;   /* path on ISO, NULL if unused */"
    echo "} ${NAME}_sfx_t;"
    echo ""
    echo "static const ${NAME}_sfx_t ${NAME}_sfx[30] = {"
    # Build a lookup from the sfx_index.txt; entries are param-indexed.
    declare -A sfx_sid sfx_freq sfx_file
    if [ -n "$SND" ] && [ -f "$SFX_STAGE/sfx_index.txt" ]; then
        while read -r idxline; do
            case "$idxline" in '#'*|'') continue ;; esac
            read -r param sid freq blen fname <<<"$idxline"
            sfx_sid[$param]="$sid"
            sfx_freq[$param]="$freq"
            sfx_file[$param]="$fname"
        done < "$SFX_STAGE/sfx_index.txt"
    fi
    for i in $(seq 0 29); do
        if [ -n "${sfx_sid[$i]:-}" ]; then
            echo "    /* [$i] */ { ${sfx_sid[$i]}, ${sfx_freq[$i]}, \"Audio/HAR_${NAME_UPPER}/${sfx_file[$i]}\" },"
        else
            echo "    /* [$i] */ { 0, 0, (const char *)0 },"
        fi
    done
    echo "};"
    echo ""
    echo "#endif"
} > "$HEADER"

echo "Pipeline OK."
echo "  $ART_DIR/ ($total_cels CELs, $((total_bytes / 1024)) KB)"
if [ -n "$SND" ]; then
    echo "  $SFX_DIR/ ($sfx_count AIFFs)"
fi
echo "  $HEADER"
