/*
 * blit_text.h -- minimal 3DO font runtime for OMF menus.
 *
 * Loads the per-glyph CELs generated by port_3do/host_tools/run_pipeline_font.sh
 * (CHARSMAL.DAT, 95 printable ASCII chars padded into 8x8 cells) and chains
 * them into a CCB list for one-shot drawing.
 *
 * Usage:
 *     if (BlitTextInit() < 0) ...;
 *     BlitTextDraw(bitmap, x, y, "HELLO 3DO");
 *     ...
 *     BlitTextShutdown();
 *
 * The glyphs are rendered white-on-transparent; tinting (PIXC) is a TODO
 * once we need colored menus. Glyph pitch is FONT_SMALL_GLYPH_W (6 px).
 */
#ifndef BLIT_TEXT_H
#define BLIT_TEXT_H

#include "types.h"
#include "graphics.h"

/* Returns 0 on success, -1 on failure. LoadCels every glyph CEL. */
int   BlitTextInit(void);

/* Frees every glyph CCB. */
void  BlitTextShutdown(void);

/* MUST be called once per frame, BEFORE any BlitTextChain/Draw calls in
 * that frame. Resets the internal CCB pool head so previously-issued
 * chains become invalid -- safe because they were submitted in the
 * previous frame's DrawCels. */
void  BlitTextBeginFrame(void);

/* Builds a CCB chain that renders `str` starting at screen (x, y).
 * Returns the head CCB (CCB_LAST set on the last glyph). Returns NULL on
 * empty / all-blank string or pool exhaustion. Multiple calls within
 * one frame each grab fresh CCBs from the pool, so duplicate letters
 * across chains (or within one chain) render correctly. */
CCB  *BlitTextChain(int x, int y, const char *str);

/* Convenience: BlitTextBeginFrame + BlitTextChain + DrawCels in one
 * call. Resets the pool internally -- do NOT mix with manual
 * BlitTextChain calls in the same frame. */
void  BlitTextDraw(Item bitmap, int x, int y, const char *str);

#endif /* BLIT_TEXT_H */
