/*
 * har_packs.c -- isolated TU that wraps the per-HAR data tables into
 * runtime-dispatchable packs.
 *
 * Only file in the project that includes both jaguar_all_data.h and
 * thorn_all_data.h (per har_packs.h preamble). The casts below are
 * safe because the per-HAR data structs are POD layout-identical with
 * the har_*_t struct types in har_packs.h (the pipeline emits one
 * typedef per HAR purely for diagnostic clarity in the auto-gen
 * headers -- field count, order and width all match exactly).
 */
#include "har_packs.h"
#include "scene_select.h"          /* SELECT_HAR_* enum */

#include "jaguar_all_data.h"
#include "thorn_all_data.h"

/* Per-move af_move scalar metadata for the openomf logic port (separate from
 * the baked frame tables — see har_packs.h har_move_meta_t). Generated by
 * `dump_har meta` directly from each AF (no CEL re-dump). Each _meta.h is
 * paired with its _all_data.h (same source AF): jaguar=FIGHTR0, thorn=FIGHTR2
 * (canonical Thorn — re-sourced 2026-05-30, was wrongly FIGHTR3=Pyros). If a
 * HAR is ever re-sourced, regenerate BOTH headers together. */
#include "jaguar_meta.h"
#include "thorn_meta.h"

#include "debug3do.h"

const har_pack_t gJaguarPack = {
    (const har_move_t *)jaguar_moves,
    (int)JAGUAR_MOVES_COUNT,
    (const har_sfx_t *)jaguar_sfx,
    "JAGUAR",
    (int)JAGUAR_BASE_HEALTH,
    /* FIGHTR0.AF: fwd=5.00 bwd=4.00 jump=-14.50 fall=1.15 (dump_har list). */
    1280, 1024, -3712, 294,
    jaguar_move_meta,
    (int)JAGUAR_MOVE_META_COUNT,
    jaguar_recoil,
    (int)JAGUAR_RECOIL_COUNT
};

const har_pack_t gThornPack = {
    (const har_move_t *)thorn_moves,
    (int)THORN_MOVES_COUNT,
    (const har_sfx_t *)thorn_sfx,
    "THORN",
    (int)THORN_BASE_HEALTH,
    /* FIGHTR2.AF: fwd=5.00 bwd=4.00 jump=-14.50 fall=1.15 (dump_har list). */
    1280, 1024, -3712, 294,
    thorn_move_meta,
    (int)THORN_MOVE_META_COUNT,
    thorn_recoil,
    (int)THORN_RECOIL_COUNT
};

const har_pack_t *gCurHarPack = &gJaguarPack;

const har_recoil_move_t *
HarPackFindRecoil(const har_pack_t *pack, int move_id)
{
    int i;
    if (pack == NULL || pack->recoil == NULL) return NULL;
    for (i = 0; i < pack->recoil_count; i++) {
        if (pack->recoil[i].id == move_id) return &pack->recoil[i];
    }
    return NULL;
}

const har_pack_t *
HarPackForId(int har_id)
{
    switch (har_id) {
    case SELECT_HAR_THORN:  return &gThornPack;
    case SELECT_HAR_JAGUAR: return &gJaguarPack;
    /* SHADOW (and any non-playable id) has no battle moveset/atlas yet --
     * fall back to Jaguar so the opponent is always a real fighter. */
    default:                return &gJaguarPack;
    }
}

const char *
HarPackSelect(int sel_har_id)
{
    switch (sel_har_id) {
    case SELECT_HAR_THORN:
        gCurHarPack = &gThornPack;
        break;
    case SELECT_HAR_SHADOW:
        /* Shadow has no per-move data set yet (only the static idle
         * frames in shadow_data.h, used as the P2 opponent). For now
         * coerce a Shadow pick to Jaguar so the game keeps running. */
        printf("har_packs: SHADOW not playable, falling back to JAGUAR\n");
        gCurHarPack = &gJaguarPack;
        break;
    case SELECT_HAR_JAGUAR:
    default:
        gCurHarPack = &gJaguarPack;
        break;
    }
    printf("har_packs: active = %s (%d moves)\n",
           gCurHarPack->name, gCurHarPack->moves_count);
    return gCurHarPack->name;
}
