/*
 * har_packs.h -- HAR-pack indirection for the runtime battle engine.
 *
 * Lets the battle scene dispatch on gSelectedHarId without hello.c
 * having to #include the per-HAR data headers directly (each header is
 * ~10-15 KLOC of static const tables -- pulling them into hello.c's TU
 * defeats armlink's gc-sections per-TU and bloats LaunchMe by ~240 KB).
 *
 * Strategy:
 *   - har_packs.c is the ONLY TU that includes jaguar_all_data.h +
 *     thorn_all_data.h. It exposes two extern pack constants whose
 *     fields point at the per-HAR tables, cast to the canonical
 *     har_*_t struct types declared below.
 *   - hello.c includes har_packs.h, never the per-HAR data headers.
 *     It iterates / indexes via gCurHarPack->moves[] etc.
 *
 * The per-HAR struct types (jaguar_move_t, thorn_move_t, ...) are
 * field-by-field LAYOUT IDENTICAL -- the only reason they have
 * different type names is that the host-side pipeline emits one
 * typedef per HAR for diagnostic clarity. Casting between them is
 * safe under C aliasing rules (compatible POD with identical members).
 */
#ifndef HAR_PACKS_H
#define HAR_PACKS_H

#include "types.h"

#define HAR_MAX_MOVES   64    /* Jaguar=43, Thorn=43 (room for future HARs) */

/* Mirror layout of jaguar_frame_t / thorn_frame_t. */
typedef struct {
    const char *cel_path;
    short pos_x, pos_y;
    short w, h;
    unsigned char missing;
    const unsigned char *mask;
} har_frame_t;

/* Mirror layout of jaguar_anim_step_t / thorn_anim_step_t. */
typedef struct {
    short sprite_idx;
    short dwell_ticks;
    short sound_param;
    short sound_freq_pitch;
    short sound_vol;
    short sound_pan;
    unsigned char flip_r;
    unsigned char flip_f;
} har_anim_step_t;

/* Mirror layout of jaguar_coord_t / thorn_coord_t. */
typedef struct {
    int x;
    int y;
    int frame_index;
} har_coord_t;

/* Mirror layout of jaguar_move_t / thorn_move_t.
 * Sessione 9 added `damage` (sd_move.damage_amount) to drive health bars;
 * field slots into the 2-byte padding hole after 5 shorts, struct size
 * unchanged on ARM (still 5 shorts -> ptr-aligned). */
typedef struct {
    short id;
    short frame_count;
    short category;
    short step_count;
    short coord_count;
    short damage;
    const har_frame_t *frames;
    const har_anim_step_t *steps;
    const har_coord_t *coords;
    const char *input;
    const char *anim_string;
} har_move_t;

/* Per-move af_move SCALAR metadata for the openomf logic port (is_in_range,
 * calc_damage_and_stun, blocking, chaining). Generated by `dump_har meta`
 * directly from the AF into src/<name>_meta.h — kept SEPARATE from the baked
 * frame tables above so adding logic fields never forces a CEL re-dump / ISO
 * churn. Field semantics mirror openomf resources/af_move.c af_move_create().
 * `category`/`damage` are duplicated from har_move_t so the shim af_move view
 * can be built from the meta entry alone (same AF source — cannot diverge). */
typedef struct {
    short         id;             /* OMF move id (matches har_move_t.id)     */
    short         category;       /* CAT_* (sd_move.category)                */
    short         damage;         /* sd_move.damage_amount                   */
    short         hit_sound;      /* footer-string impact sound param 0..29; -1 = none (the "clang") */
    short         knockback_x;    /* net footer x-displacement (OMF px), + = pushed backward */
    short         recoil_ticks;   /* footer duration in ticks (recoil/slide length) */
    unsigned char next_move;      /* sd_move.next_anim_id                    */
    unsigned char successor_id;   /* throw distance req (sd_move.successor_id)*/
    unsigned char block_damage;   /* sd_move.block_damage                    */
    unsigned char block_stun;     /* sd_move.block_stun                      */
    unsigned char throw_duration; /* sd_move.throw_duration                  */
    int           points;         /* sd_move.points * 400 (af_move semantics)*/
} har_move_meta_t;

/* Mirror layout of jaguar_sfx_t / thorn_sfx_t. */
typedef struct {
    short sound_id;
    int   freq_hz;
    const char *aiff_path;
} har_sfx_t;

/* Victim hit-reaction (recoil) track, baked per attacker move by `dump_har
 * meta`. openomf plays the attacker move's footer_string over the victim's
 * ANIM_DAMAGE animation (har.c:980/1032); each footer frame picks an
 * ANIM_DAMAGE sprite, holds `ticks`, and shifts the victim by `dx` world px
 * (one-shot position delta, already signed for our fixed P2-faces-left
 * layout = footer (x-) minus (x+); +dx = pushed backward/right). */
typedef struct {
    short sprite;   /* index into the victim's ANIM_DAMAGE frame list */
    short ticks;    /* footer frame tick_len */
    short dx;       /* +backward (right). pos: one-shot world delta. vel: px/tick */
    short dy;       /* -up / +down (footer 'y-' tag). vel: px/tick launch; pos: delta */
    short is_vel;   /* 1 => dx/dy are VELOCITIES (friction+gravity), not deltas */
} har_recoil_frame_t;

typedef struct {
    short id;                          /* attacker move id (matches har_move_t.id) */
    short count;                       /* number of frames in `frames` */
    const har_recoil_frame_t *frames;
} har_recoil_move_t;

typedef struct {
    const har_move_t *moves;        /* MAX_HAR_MOVES * sizeof(har_move_t) */
    int               moves_count;
    const har_sfx_t  *sfx;          /* 30 entries -- 1:1 with sd_af_file.soundtable */
    const char       *name;
    int               base_health;  /* OMF af.health raw (Jaguar=200, Thorn=220) */
    /* AF movement scalars, x256 fixed-point, transcribed verbatim from the AF
     * via `dump_har list` (same source-faithful pattern as pilot_stats.c).
     * Scaled at runtime by pilot agility with the canon formula
     * (openomf har.c:2716) to drive jump/walk physics. jump is NEGATIVE (up).
     * TODO: auto-emit these from dump_har's AF_INFO line like base_health. */
    int               af_fwd_x256;   /* forward_speed * 256 */
    int               af_bwd_x256;   /* reverse_speed * 256 */
    int               af_jump_x256;  /* jump_speed    * 256 (negative = up) */
    int               af_fall_x256;  /* fall_speed    * 256 */
    const har_move_meta_t *meta;    /* per-move af_move scalar metadata (logic port) */
    int               meta_count;
    const har_recoil_move_t *recoil; /* per-move victim recoil tracks (footer-derived) */
    int               recoil_count;
} har_pack_t;

/* Find the recoil track for an attacker move id in a pack, or NULL. */
const har_recoil_move_t *HarPackFindRecoil(const har_pack_t *pack, int move_id);

/* Defined in har_packs.c. */
extern const har_pack_t gJaguarPack;
extern const har_pack_t gThornPack;

/* The currently-active pack. Defaults to gJaguarPack at startup;
 * HarPackSelect(id) reassigns based on gSelectedHarId. */
extern const har_pack_t *gCurHarPack;

/* Choose the pack for the upcoming battle. Maps:
 *   SELECT_HAR_JAGUAR -> gJaguarPack
 *   SELECT_HAR_THORN  -> gThornPack
 *   SELECT_HAR_SHADOW -> gJaguarPack (Shadow has no battle move set;
 *                       falls back so the game keeps running)
 *   any other         -> gJaguarPack
 * Returns the chosen pack's name (debug-friendly). */
const char *HarPackSelect(int sel_har_id);

/* Like HarPackSelect's mapping but PURE: returns the playable pack for a HAR id
 * WITHOUT touching gCurHarPack. Used to resolve the P2 opponent pack from
 * gOpponentHarId (MILESTONE_1V1 §1.1). JAGUAR/anything-unplayable -> gJaguarPack,
 * THORN -> gThornPack. Mirror matches (id == P1's) resolve fine: caller loads a
 * separate atlas instance for P2. */
const har_pack_t *HarPackForId(int har_id);

#endif /* HAR_PACKS_H */
