#ifndef SD_ERROR_H
#define SD_ERROR_H
enum SD_ERRORCODE {
    SD_SUCCESS,
    SD_FILE_OPEN_ERROR,
    SD_FILE_INVALID_TYPE,
    SD_FILE_READ_ERROR,
    SD_OUT_OF_MEMORY,
    SD_INVALID_INPUT,
    SD_FORMAT_NOT_SUPPORTED,
    SD_FAILURE
};
#endif
